name: Jean-Richard Lai
description: Code and other things
meta_keywords: web developer, ruby on rails developer, web 2.0, react, react-native
meta_description: "Jean-Richard lai web 2.0 Ruby on Rails Developer"

aboutPage: true

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'http://jrichardlai.com'
google_analytics: 'UA-15492959-1'
disqus: true
disqus_shortname: 'jrichardlai'

# Details for the RSS feed generator
url:            'http://jrichardlai.com'
author:         'Jean-Richard Lai'
authorTwitter:  'jrichardlai'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post

exclude: [vendor]
